### ISSUE TITLE
Pi Zero case model does not 'build'

### ISSUE THREAD

**Issue by BNNorman** [paulgeneres/OpenSCAD-Projects#1]
There are a number of missing (and unused) module parameters in the 'Raspberry Pi Zero Case.scad' file which causes openSCAD to complain and the model is not created.

For example top_thickness() and bottom_thickness() appear to be missing. I defined those as:-
```
function top_thickness() = wall_thickness();
function bottom_thickness() = wall_thickness();
```

Also, lib_enclosure.scad expects parameters like **is_bottom** to be handled by several modules which actually don't use the parameter. That causes openSCAD to complain.

I just changed those modules from e.g.:-
```
module right_cutouts() {
	square_cutout(csi[0], csi[1]); // camera
}
```
by adding a parameter 'x' to
```
module right_cutouts(x) {
	square_cutout(csi[0], csi[1]); // camera
}
```

And that stopped openSCAD complaining. - the model then built ok. Well, I haven't actually printed it yet - I wanted to extend the width to allow fitting of an RTC.

Thanks for this work though, I'm sure it will be useful.

**Comment by paul1522** [comment]
Thanks for the info. It's been quite a while since I've looked at any of this. I probably have some updates that need to be pushed. What version of Open SCAD are you using?

**Comment by BNNorman** [comment]
Yeah, I figured openSCAD version might be why it didn't like missing parameters. I'm using 2019.05 - just seen 2021.01 is available so I'll update mine.

**Comment by paul1522** [comment]
Commit 4b4c7f4cf6f6434b53074a4a8442131fa16efd73 has the version of `lib_enclosure3.scad` that `Raspberry Pi Zero Case.scad` is looking for. Sorry that the repo is such a mess. It's just sort of a dumping ground for every half baked idea I ever had. I never thought anybody but me would ever look at it. The "Too many unnamed arguments supplied" warnings are benign as far as I can tell. I don't remember seeing them before so it must be something new to OpenSCAD. Someday I will update it to use the new `lib_enclosure.scad`. Thanks for the feedback.

**Comment by BNNorman** [comment]
No problem - I got that. I use some repros for storage too.
